/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.proyecto_fase2_202010223;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author angel
 */
public class Vcliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente cliente;

    public Vcliente(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        actualizar();
    }

    private Vcliente() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualizador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        ComboCapas = new javax.swing.JComboBox<>();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        ComboImagenes = new javax.swing.JComboBox<>();
        b9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboRecorrido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CombocantidadCapas = new javax.swing.JComboBox<>();
        b10 = new javax.swing.JButton();
        Lrecorrido = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        variascapas = new javax.swing.JTextField();
        Jlabel6 = new javax.swing.JLabel();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        idImagenG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        b1.setText("Capas");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("Imagenes");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("Albunes");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        visualizador.setBackground(new java.awt.Color(255, 255, 255));
        visualizador.setForeground(new java.awt.Color(0, 0, 0));
        visualizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        visualizador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visualizador.setOpaque(true);
        jScrollPane1.setViewportView(visualizador);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cargas Masivas");

        b4.setText("Cerrar sesión");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("Ver Arbol de capas");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        ComboCapas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        b6.setText("Ver capa");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("Ver capa logica");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("Ver Arbol de imagenes");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        ComboImagenes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        b9.setText("Ver imagen");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Imagen por recorrido limitado");

        ComboRecorrido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ComboRecorrido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preorder", "Inorder", "Postorder" }));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de capas a realizar:");

        CombocantidadCapas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        b10.setText("Ver imagen del recorrido");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        Lrecorrido.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Lrecorrido.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Ver capas de la imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        variascapas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Jlabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Jlabel6.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel6.setText("Ver varias capas a la vez:\n(separadas por coma)");

        b11.setText("Ver capas");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setText("Ver lista de Album");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setText("Guardar Imagen");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        idImagenG.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(32, 32, 32))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(ComboCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(b9)
                                            .addComponent(ComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(ComboRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(CombocantidadCapas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lrecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(variascapas)
                                        .addComponent(Jlabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idImagenG, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b8)
                    .addComponent(b12)
                    .addComponent(b5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6)
                    .addComponent(b9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7)
                    .addComponent(jButton2))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(ComboRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CombocantidadCapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(b10)
                .addGap(28, 28, 28)
                .addComponent(Lrecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(variascapas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b13)
                    .addComponent(idImagenG, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        carga_albunes();
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        this.carga_capas();
//        this.dispose();
//        Vcliente c = new Vcliente(cliente);
//        c.setVisible(true);


    }//GEN-LAST:event_b1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        try {
            Path ruta = Paths.get("arbolCapas.png");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoCapas.dot");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoCapa.png");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoCapa.dot");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoImagen.png");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoImagen.dot");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("arbolImagenes.png");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoImagenes.dot");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoAlbum.png");
            Files.deleteIfExists(ruta);
            ruta = Paths.get("graficoAlbum.dot");
            Files.deleteIfExists(ruta);
        } catch (Exception e) {
            e.printStackTrace();
        }
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        try {
            String dot = cliente.capas.graficar();
            FileWriter f = new FileWriter("graficoCapas.dot");
            BufferedWriter bufer = new BufferedWriter(f);
            bufer.write(dot);
            bufer.close();
            ProcessBuilder p = new ProcessBuilder("dot", "-Tpng", "graficoCapas.dot", "-o", "arbolCapas.png");
            p.redirectErrorStream(true);
            p.start();
            java.util.concurrent.TimeUnit.SECONDS.sleep(1);
            File archivo = new File("arbolCapas.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(icono);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        carga_imagenes();
    }//GEN-LAST:event_b2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        try{
            int numero=Integer.parseInt(ComboCapas.getSelectedItem().toString());
            cliente.capas.graficarcapa(numero);
            File archivo = new File("graficoCapa.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        try{
            int numero=Integer.parseInt(ComboCapas.getSelectedItem().toString());
            cliente.capas.graficarcapalogica(numero);
            JOptionPane.showMessageDialog(this, "Capa generada con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            File archivo = new File("graficoCapa.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        //ver Arbol de imagenes
        try {
            String dot = cliente.imagenes.graficar();
            FileWriter f = new FileWriter("graficoImagenes.dot");
            BufferedWriter bufer = new BufferedWriter(f);
            bufer.write(dot);
            bufer.close();
            ProcessBuilder p = new ProcessBuilder("dot", "-Tpng", "graficoImagenes.dot", "-o", "arbolImagenes.png");
            p.redirectErrorStream(true);
            p.start();
            java.util.concurrent.TimeUnit.SECONDS.sleep(1);
            File archivo = new File("arbolImagenes.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        //boton para ver imagen del combobox
        try{
            int numero=Integer.parseInt(ComboImagenes.getSelectedItem().toString());
            cliente.imagenes.graficarimagen(numero);
            File archivo = new File("graficoImagen.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        int tipo=ComboRecorrido.getSelectedIndex();
        int cantidad=Integer.parseInt(CombocantidadCapas.getSelectedItem().toString());
        cliente.capas.recorrer(tipo, cantidad);
        try{
            File archivo = new File("graficoImagen.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
            Lrecorrido.setText(cliente.capas.capas);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //boton mostrar arbol de capas de una imagen en especifico
        
        try {
            int numero=Integer.parseInt(ComboImagenes.getSelectedItem().toString());
            Imagen i=cliente.imagenes.buscar_retornar(numero);
            String dot = i.capas.graficar();
            FileWriter f = new FileWriter("graficoCapas.dot");
            BufferedWriter bufer = new BufferedWriter(f);
            bufer.write(dot);
            bufer.close();
            ProcessBuilder p = new ProcessBuilder("dot", "-Tpng", "graficoCapas.dot", "-o", "arbolCapas.png");
            p.redirectErrorStream(true);
            p.start();
            java.util.concurrent.TimeUnit.SECONDS.sleep(1);
            File archivo = new File("arbolCapas.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        //boton de ver varias capas a la vez
        try{
            String texto=variascapas.getText();
            //System.out.println(texto);
            String [] capas=texto.split(",");
            Imagen nueva=new Imagen(0);
            for (int i = 0; i < capas.length; i++) {
                int numero=Integer.parseInt(capas[i]);
                Capa c=cliente.capas.buscarcapa(numero);
                if(c!=null){
                    nueva.agregarcapa(c);
                }
            }
            nueva.Mimagen.graficar_matriz2();
            File archivo = new File("graficoCapa.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        try {
            cliente.Albunes.mostrar_grafico();
            java.util.concurrent.TimeUnit.SECONDS.sleep(1);
            File archivo = new File("graficoAlbum.png");
            BufferedImage buffer = ImageIO.read(archivo);
            ImageIcon imagen = new ImageIcon(buffer);
            Icon icono = new ImageIcon(imagen.getImage());
            visualizador.setIcon(null);
            visualizador.setIcon(icono);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        int id;
        try{
            id=Integer.parseInt(idImagenG.getText());
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Entrada incorrecta", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            String texto=variascapas.getText();
            //System.out.println(texto);
            String [] capas=texto.split(",");
            Imagen nueva=new Imagen(id);
            for (int i = 0; i < capas.length; i++) {
                int numero=Integer.parseInt(capas[i]);
                Capa c=cliente.capas.buscarcapa(numero);
                if(c!=null){
                    nueva.agregarcapa(c);
                }
            }
            cliente.imagenes.insertar(nueva);
            JOptionPane.showMessageDialog(this, "Proceso completado", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            actualizar();
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_b13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vcliente().setVisible(true);
            }
        });
    }

    public void carga_capas() {
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter Filter = new FileNameExtensionFilter("Archivos JSON", "json");
        jfc.setFileFilter(Filter);
        jfc.showOpenDialog(null);
        File archivo = jfc.getSelectedFile();
        //System.out.println(archivo); //imprime ruta absoluta

        if (archivo != null) {
            try {
                BufferedReader obj = new BufferedReader(new FileReader(archivo));
                String texto = "";
                String contenido = "";
                while ((texto = obj.readLine()) != null) {
                    contenido += texto + "\n";
                }
                contenido = contenido.toUpperCase();

                JsonParser parser = new JsonParser();
                JsonArray arreglo = parser.parse(contenido).getAsJsonArray();
                //Matriz nueva=new Matriz("COMPLETA");
                for (int i = 0; i < arreglo.size(); i++) {
                    JsonObject objeto = arreglo.get(i).getAsJsonObject();
                    int idcapa = objeto.get("ID_CAPA").getAsInt();
                    JsonArray pixeles = objeto.get("PIXELES").getAsJsonArray();
                    //System.out.println("capa"+idcapa);
                    Matriz nueva = new Matriz("CAPA" + idcapa);
                    for (int j = 0; j < pixeles.size(); j++) {
                        JsonObject p = pixeles.get(j).getAsJsonObject();
                        int y = p.get("FILA").getAsInt();
                        int x = p.get("COLUMNA").getAsInt();
                        String color = p.get("COLOR").getAsString();
                        //System.out.println("coordenada x="+x+" y="+y+" color"+color);
                        nueva.insertarNodo(x, y, color);
                    }
                    Capa c = new Capa(idcapa, nueva);
                    cliente.capas.insertar(c);
                }
                JOptionPane.showMessageDialog(this, "Capas cargadas con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                actualizar();
                

            } catch (Exception e) {
                System.out.println("Error en la lectura del archivo");
                e.printStackTrace();
            }
        }

    }
    
    public void carga_imagenes() {
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter Filter = new FileNameExtensionFilter("Archivos JSON", "json");
        jfc.setFileFilter(Filter);
        jfc.showOpenDialog(null);
        File archivo = jfc.getSelectedFile();
        //System.out.println(archivo); //imprime ruta absoluta

        if (archivo != null) {
            try {
                BufferedReader obj = new BufferedReader(new FileReader(archivo));
                String texto = "";
                String contenido = "";
                while ((texto = obj.readLine()) != null) {
                    contenido += texto + "\n";
                }
                contenido = contenido.toUpperCase();

                JsonParser parser = new JsonParser();
                JsonArray arreglo = parser.parse(contenido).getAsJsonArray();
                for (int i = 0; i < arreglo.size(); i++) {
                    JsonObject objeto = arreglo.get(i).getAsJsonObject();
                    int id = objeto.get("ID").getAsInt();
                    Imagen nueva=new Imagen(id);
                    JsonArray capas = objeto.get("CAPAS").getAsJsonArray();
                    //System.out.println("capas de la imagen---------------");
                    for (int j = 0; j < capas.size(); j++) {
                        nueva.agregarcapa(cliente.capas.buscarcapa(capas.get(j).getAsInt()));
                        //System.out.println(capas.get(j));
                    }
                    //System.out.println(nueva.capas.graficar());
                    cliente.imagenes.insertar(nueva);
                }
                //cliente.imagenes.graficar();
                JOptionPane.showMessageDialog(this, "Imagenes cargadas con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                actualizar();
                

            } catch (Exception e) {
                System.out.println("Error en la lectura del archivo");
                e.printStackTrace();
            }
        }

    }
    
    public void carga_albunes() {
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter Filter = new FileNameExtensionFilter("Archivos JSON", "json");
        jfc.setFileFilter(Filter);
        jfc.showOpenDialog(null);
        File archivo = jfc.getSelectedFile();
        //System.out.println(archivo); //imprime ruta absoluta

        if (archivo != null) {
            try {
                BufferedReader obj = new BufferedReader(new FileReader(archivo));
                String texto = "";
                String contenido = "";
                while ((texto = obj.readLine()) != null) {
                    contenido += texto + "\n";
                }
                contenido = contenido.toUpperCase();

                JsonParser parser = new JsonParser();
                JsonArray arreglo = parser.parse(contenido).getAsJsonArray();
                for (int i = 0; i < arreglo.size(); i++) {
                    JsonObject objeto = arreglo.get(i).getAsJsonObject();
                    String nombre = objeto.get("NOMBRE_ALBUM").getAsString();
                    JsonArray imagenes = objeto.get("IMGS").getAsJsonArray();
                    //System.out.println("imagenes del album---------------");
                    Listaimagenes lista=new Listaimagenes();
                    for (int j = 0; j < imagenes.size(); j++) {
                        Imagen img=cliente.imagenes.buscar_retornar(imagenes.get(j).getAsInt());
                        if(img!=null){
                            lista.insertar(img);
                        }
                    }
                    Album nuevo= new Album(nombre,lista);
                    cliente.Albunes.insertar(nuevo);
                }
                //cliente.imagenes.graficar();
                JOptionPane.showMessageDialog(this, "Imagenes cargadas con exito", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                actualizar();
                

            } catch (Exception e) {
                System.out.println("Error en la lectura del archivo");
                e.printStackTrace();
            }
        }

    }

    public void actualizar(){
        setTitle(cliente.getNombre());
        ComboCapas.removeAllItems();
        cliente.capas.combocapas(cliente.capas.raiz, this);
        ComboImagenes.removeAllItems();
        cliente.imagenes.comboimagenes(cliente.imagenes.raiz, this);
        CombocantidadCapas.removeAllItems();
        cliente.capas.comboCantidad(this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboCapas;
    public javax.swing.JComboBox<String> ComboImagenes;
    private javax.swing.JComboBox<String> ComboRecorrido;
    public javax.swing.JComboBox<String> CombocantidadCapas;
    private javax.swing.JLabel Jlabel6;
    private javax.swing.JLabel Lrecorrido;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JTextField idImagenG;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField variascapas;
    private javax.swing.JLabel visualizador;
    // End of variables declaration//GEN-END:variables
}
